FROM ruby:2.5-alpine
MAINTAINER openHPI team <openhpi-info@hpi.de>

RUN read command; exec $command

# Install gems for testing
RUN gem install rspec rspec-expectations

VOLUME /workspace
WORKDIR /workspace
