name: "Publish Julia:1.8 image"

on: workflow_dispatch

env:
  IMAGE_NAME: co_execenv_julia
  IMAGE_TAG: 1.8

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.IMAGE_NAME }}/${{ env.IMAGE_TAG }}
          # Cross-compiling for linux/arm64 won't work. See https://github.com/JuliaLang/julia/issues/49474
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
